<?php

// PHP Data Model definition file

// WARNING - WARNING - WARNING
// DO NOT EDIT THIS FILE (unless you know what you are doing)
//
// If you use supply a datamodel.xxxx.xml file with your module
// the this file WILL BE overwritten by the compilation of the
// module (during the setup) if the datamodel.xxxx.xml file
// contains the definition of new classes or menus.
//
// The recommended way to define new classes (for iTop 2.0) is via the XML definition.
// This file remains in the module's template only for the cases where there is:
// - either no new class or menu defined in the XML file
// - or no XML file at all supplied by the module

function isAdmin()
{
	if(isset($_SESSION['profile_list']))
	{
		if(array_key_exists("1", $_SESSION['profile_list']))
		{
			return(true);
		}
	}
	return(false);
}

$appRootUrl = trim(MetaModel::GetConfig()->Get('app_root_url'));
if(isset($_GET["operation"]) && isset($_GET["class"]) && !isAdmin())
{
	if($_GET["operation"] == "new" && $_GET["class"] == "UserRequest")
	{
		$location = "$appRootUrl" . "portal/index.php?operation=create_request";
		header("Location: $location");
	}
}
