<?php

// PHP Data Model definition file

// WARNING - WARNING - WARNING
// DO NOT EDIT THIS FILE (unless you know what you are doing)
//
// If you use supply a datamodel.xxxx.xml file with your module
// the this file WILL BE overwritten by the compilation of the
// module (during the setup) if the datamodel.xxxx.xml file
// contains the definition of new classes or menus.
//
// The recommended way to define new classes (for iTop 2.0) is via the XML definition.
// This file remains in the module's template only for the cases where there is:
// - either no new class or menu defined in the XML file
// - or no XML file at all supplied by the module

//cron任务忽略sso认证
if(isset($_SERVER['REQUEST_URI']))
{
	//如果访问 toolkit 或者 setup 等工具页面，则不跳转到sso
	if(preg_match('/^\/toolkit\/|^\/webservices\/|^\/setup\//i',$_SERVER['REQUEST_URI']))
	{
		return true;
	}
}

// 登录后才检查，防止和sso检查代码冲突
$rootUrl = trim(MetaModel::GetConfig()->Get('app_root_url'));
if(isset($_SESSION['auth_user'])) {
	$location = $rootUrl . "env-production/custom-pages/verify_user.php";
	if(!isset($_SESSION['verify_user'])) {
		$_SESSION['verify_user'] = 0;
		header("Location: $location");
	}

	if(isset($_SESSION['verify_user']) && $_SESSION['verify_user'] != 1) {
		$re = '/pages\/UI\.php\?operation=modify&class=Person&id=[0-9]+|.*\/verify_user\.php.*|pages\/logoff\.php.*/i';
		if(!preg_match($re, $_SERVER['REQUEST_URI']))
		{
			header("Location: $location");
		}
	}
} else {
	unset($_SESSION['verify_user']);
}
